targets:
  $default:
    sources:
      - lib/**
      - swaggers/**
      - swaggers2/**
      - input_folder/**
      - swagger_examples/**
      - $package$
    builders:
      chopper_generator:
        options:
          header: "//Generated code"
      swagger_dart_code_generator:
        options:
          input_folder: "input_folder/"
          output_folder: "lib/swagger_generated_code/"
          input_urls:
            - url: "https://sarovar-api.krida.top/swagger-store-employee-app/json"
              file_name: "store_api.json"
          with_base_url: true
          with_converter: true
          use_path_for_request_names: true
          use_default_null_for_lists: true
          override_equals_and_hashcode: true
          build_only_models: false
          separate_models: false
          enums_case_sensitive: false
          ignore_headers: false
          use_required_attribute_for_headers: false
          include_if_null: true
          
          
          