// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9LZLAp6yIIXdWBl7L7U6Ub4HGsJyvUZI',
    appId: '1:356466483583:web:02a08d3710dd4658f2fa4a',
    messagingSenderId: '356466483583',
    projectId: 'astrokoolam-cd0dd',
    authDomain: 'astrokoolam-cd0dd.firebaseapp.com',
    databaseURL:
        'https://astrokoolam-cd0dd-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'astrokoolam-cd0dd.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZ-WcUfk4nPHh15PTaKM_v68L-tCCAHqs',
    appId: '1:356466483583:android:454eb248bab06e9af2fa4a',
    messagingSenderId: '356466483583',
    projectId: 'astrokoolam-cd0dd',
    databaseURL:
        'https://astrokoolam-cd0dd-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'astrokoolam-cd0dd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBF9zy75CQB7XnbllPdSmtZ3xgaPAs5Qwo',
    appId: '1:356466483583:ios:c8c676266d5397dbf2fa4a',
    messagingSenderId: '356466483583',
    projectId: 'astrokoolam-cd0dd',
    databaseURL:
        'https://astrokoolam-cd0dd-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'astrokoolam-cd0dd.appspot.com',
    iosBundleId: 'com.astrokoolam.app.testProject',
  );
}
